name: Storybook

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Github Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          checkout: true
          install_command: npm ci
          build_command: npm run build:storybook
          path: storybook-static